### ISSUE TITLE
TO-DO List for Version 0.0.1

### ISSUE THREAD

**Issue by DefinitlyEvil** [DragonetMC/Dragonet-Legacy#1]
- [X] Basic Networking
- [X] PlayerJoining
- [X] Map transmitting
- [X] Player Movement
- [x] Block/Item Translation
- [x] PE-side inventory support
- [x] PE-side block updating
- [x] PE block action handling
- [x] Crafting
- [x] Add more third-party libraries to support more plugins

**Comment by optrusty** [comment]
I got a VPS that is clean it has 128MB of RAM, 10GB of disk space, but I need to get approved
I can even setup SSL and Cron Jobs to wget from a repository that has all the website files @DefinitlyEvil

**Comment by DefinitlyEvil** [comment]
@optrusty 128MB is too small. I will have a sponsor soon and they probably will give me a VPS to do these work. :)

**Comment by ghost** [comment]
@DefinitlyEvil Yay! Finally v0.0.1!

**Comment by DefinitlyEvil** [comment]
@64FF00 But still loads of bugs.

**Comment by ghost** [comment]
@DefinitlyEvil But still :+1:

**Comment by DefinitlyEvil** [comment]
@64FF00 You can try out everything on the test server for now. :)
