### ISSUE TITLE
Loose coupling between Glowstone++ and Dragonet

### ISSUE THREAD

**Issue by jlirochon** [DragonetMC/Dragonet-Legacy#128]
When working on re-importing Glowstone++ history and re-applying Dragonet patch (#123) I realized that the patch was quite big, and could be reduced by doing some refactoring.

The patch was making Glowstone++ importing stuff from Dragonet, and both were dependent of each other. It was a nightmare to configure the IDE to handle circular dependencies.

I managed to remove unwanted dependencies by creating Interfaces, and I am still on my way to reduce the overall patch size and make things as clean as possible.

This could take a couple of days since it may requires cooperation of **GlowstonePlusPlus** and **Glowkit** projects.
# ToDo
- [x] remove org.dragonet.\* imports from Glowstone++
- [x] refactor Dragonet translators so we don't have to make Glowstone++ message properties public
- [x] make **Glowkit** project accept a contributed [pull request](https://github.com/GlowstonePlusPlus/Glowkit/pull/5) about the `PluginManager` interface, or keep the patch if they don't want to
- [x] come with a clean [pull request](https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/pull/113) to **Glowstone++** which makes possible to launch a `GlowServer` from another application
- [x] make **Glowstone++** project accept the PR, or keep the patch if they don't want to
- [ ] move calls to `Rhino` outside of **Glowstone++**'s `EventFactory`. Must be moved somewhere else in **Dragonet** (actually I commented this out to make the project compile). See #135
- [ ] come with a clean PR to **Glowstone++** to make integration with servers like Dragonet a feature of Glowstone++
- [ ] make **Glowstone++** project accept the PR, or keep the patch if they don't want to

**Comment by DefinitlyEvil** [comment]
Maybe we should make enhanced G++ a PR to them, so it can be benifit to lot of more people. ;)

**Comment by jlirochon** [comment]
Yes that's what I want to do. 

Not sure it can benefit to "lots of people", but it could be a feature of Glowstone++. 

Need to talk with @mastercoms to clarify the possibilities. We already talked about being a plugin, but it seems we are interacting at a lower level.

**Comment by RazvanDu** [comment]
Or... We could make our own server for MCPC just like G++ :p

**Comment by jlirochon** [comment]
Lol much work involved here

The plugin approach is interesting because it could be compatible with patched official servers too, not only Glowstone++. But I guess existing plugins API are not designed to let plugins handle network connections.

**Comment by mastercoms** [comment]
https://github.com/aadnk/ProtocolLib

**Comment by DefinitlyEvil** [comment]
@mastercoms ProtocolLib forced to use Minecraft source(aka NMS) to use network related things but that won't work in Glowstone since it is completely written from scratch.

**Comment by mastercoms** [comment]
I know, but if you were going the plugin route, you could be a plugin for nms servers, like CraftBukkit or Spigot.

**Comment by DefinitlyEvil** [comment]
@mastercoms That's true but people only make plugin for Bukkit or NMS, they don't know much about G++ unless we make an NMS interface. :P
