### ISSUE TITLE
TO-DO List for Version 0.0.2

### ISSUE THREAD

**Issue by DefinitlyEvil** [DragonetMC/Dragonet-Legacy#8]
New Features: 
- [x] Teleport support (use /tp)<br />
  (REMOVED) Other containers supporting
- [x] Sign content update
- [x] Entity support

Bug Fixes: 
- [x] Fix crash due to world change
- [x] Fix crash due to gamemode change
- [x] MCPE 0.10.5 Support
- [x] MCPE 0.11.0 Support (April 12th, 2015) @TheMCPEGamer 
- [x] Issue #10
- [ ] Block placing lag
- [ ] Item crafting lag

**Comment by MobileCrafter** [comment]
iOS, Windows Phone, Amazon Fire TV do not have Blocklauncher.
So only Android will have PC Blocks?

**Comment by DefinitlyEvil** [comment]
@MobileCrafter Yes, and server can identify which one installed our custom ModScript and only apply PC blocks to those clients.

**Comment by DefinitlyEvil** [comment]
@TheMCPEGamer We should prepare for the release of 0.11.0.

**Comment by Creeperface01** [comment]
0.11.0 is maked better for multiplayer right?

**Comment by DefinitlyEvil** [comment]
@TheMCPEGamer I don't know yet, I just heard that there is a 0.11.0 came out.

**Comment by TheMCPEGamer** [comment]
@DefinitlyEvil It's a beta, and I don't have an Android device to test it on.

**Comment by DefinitlyEvil** [comment]
@TheMCPEGamer Just look at pocketmine code I think.

**Comment by wordandahalf** [comment]
Are we going to 'delay' the release of 0.0.2 to when 0.11.x is released fully?

**Comment by DefinitlyEvil** [comment]
Yes. :)

**Comment by wordandahalf** [comment]
@DefinitlyEvil Since we are nearly finished with 0.0.2, should I start developing a GUI wrapper?

**Comment by RandomAltThing** [comment]
@TheMCPEGamer I thought **you** were the lead developer in this now, according to MinecraftForums

**Comment by wordandahalf** [comment]
@RandomAltThing I don't like doing things without prior approval, but I guess you're right.

**Comment by RandomAltThing** [comment]
@TheMCPEGamer Is the next update going to be <code>0.0.3</code>?

**Comment by wordandahalf** [comment]
@RandomAltThing Depending on how much we add.

**Comment by RandomAltThing** [comment]
@TheMCPEGamer Alright. I was asking so I could add a Milestone. By the way do you know what the test server IP is?

**Comment by DefinitlyEvil** [comment]
@RandomAltThing The test server isn't ready yet. @TekkitCommando 's computer is dead. xD

**Comment by Creeperface01** [comment]
Remove ModPE support from TODO list

**Comment by mastercoms** [comment]
@DefinitlyEvil He fixed it.

**Comment by RandomAltThing** [comment]
Will do

**Comment by wordandahalf** [comment]
@mastercoms I just added some code for the hostile mobs. Should I send a PR to Glowstone++ or just commit it here?

**Comment by ethsmith** [comment]
@TheMCPEGamer send a pr I gotta finish that stuff anyways xD

**Comment by wordandahalf** [comment]
@TekkitCommando OK :D

**Comment by mastercoms** [comment]
You should merge from upstream. Glowstone++ has new features, bug fixes, and huge optimizations since you last merged.

**Comment by DefinitlyEvil** [comment]
@mastercoms @TekkitCommando He will do that for me. xD Everytime I have to download fresh Glowstone++ files and change file by file to update Glowstone++ code.

**Comment by mastercoms** [comment]
What are you doing to merge?

This is what you should be doing:

Do this once:
```bash
git remote add GlowstonePlusPlus https://github.com/GlowstonePlusPlus/GlowstonePlusPlus.git
```

Then every time you want to merge, do this:
```bash
git fetch GlowstonePlusPlus
git merge GlowstonePlusPlus/master
```

**Comment by DefinitlyEvil** [comment]
@mastercoms That's a little bit complex, @TekkitCommando help help help! xD

**Comment by RandomAltThing** [comment]
I know 

``Bash
git commit
git push
git pull
git add
git remote
git status
```

But that's all

**Comment by mastercoms** [comment]
@DefinitlyEvil Not really, it is just copying and pasting commands and moving files around. It is a bit long, but that's because you don't have a normal repo structure.

**Comment by mastercoms** [comment]
If you were to separate the Dragonet and Glowkit repositories, it would be a lot easier.

**Comment by ethsmith** [comment]
^

**Comment by ethsmith** [comment]
xD

**Comment by ethsmith** [comment]
I am a bit busy today, and @mastercoms is right :P, I thought you meant to send a pull request over to you guys everytime we updated glowstone++ I didn't really look at your structure much :P

**Comment by DefinitlyEvil** [comment]
@TekkitCommando Glowstone++ files are under `Dragonet-core/src`

**Comment by DefinitlyEvil** [comment]
@mastercoms I will try your way but I am not a good 'gitter' you know. xD

**Comment by RandomAltThing** [comment]
@DefinitlyEvil 'gitter' is an online chat for github repositories. I'm assuming with mean 'git' which has stuff like <code>git push</code> etc

**Comment by mastercoms** [comment]
gitter as in someone who uses git. Like teacher is someone who teaches, sailor is someone who sails, etc.

**Comment by TekkitCommando** [comment]
and eater is someone who eats a lot and thats me xD

**Comment by RandomAltThing** [comment]
@mastercoms gitter.im

**Comment by RandomAltThing** [comment]
@mastercoms Try https://gitter.im

**Comment by mastercoms** [comment]
I know about gitter, we have one for Glowstone++. I am talking about what @DefinitlyEvil meant.

**Comment by TekkitCommando** [comment]
@RandomAltThing you trying to pick a fight xD ???

**Comment by RandomAltThing** [comment]
@TekkitCommando Come at me

**Comment by TekkitCommando** [comment]
@RandomAltThing Your Lucky @mastercoms is holding me back or i'd be in a world of hurt xD lol

**Comment by RandomAltThing** [comment]
@TekkitCommando Sorry what was that?

**Comment by mastercoms** [comment]
Can we stop?

**Comment by mastercoms** [comment]
What is block placing lag and item crafting lag? Is there a relevant issue?

**Comment by DefinitlyEvil** [comment]
@mastercoms There are some protocol issues, I have to guess and debug what each packet does.

**Comment by RandomAltThing** [comment]
@DefinitlyEvil Do you just wanted to call it 0.0.2 now? This block and item placing lag could be fixed in 0.0.3.

**Comment by DefinitlyEvil** [comment]
@RandomAltThing Probably yes, I'm busy with my work so I don't have much time doing this. :(

**Comment by RandomAltThing** [comment]
@DefinitlyEvil Alright I'm making a commit
