### ISSUE TITLE
TO-DO List For MCPE 0.13.0

### ISSUE THREAD

**Issue by DefinitlyEvil** [DragonetMC/Dragonet-Legacy#98]
### To-Do List
- [x] Redstone support(EASY)
- [x] Network/Packet Lag
## Bug List
- [x] Invisible body with fire, blank skin! #91 
- [ ] No inventory items in creative. #104 
- [ ] Not properly handled disconnection. #106 
- [x] Server discovery issue. #107 
- [x] Inventory issue. #109 
- [ ] MCPE clients are too `synchornized` lol #111 
- [ ] MCPE clients are not able to break blocks by default DiggingMessage translated. 

Comment about more. :D

**Comment by DefinitlyEvil** [comment]
@jython234 Will you please help a bit? Thanks. :P I am still not be able to use JRakLib well so I removed it for now so if you have any free time please help to integrate JRakLib thx.

**Comment by RazvanDu** [comment]
I'll give a shot at fixing the fireball bug, I will at least add a temporary fix that gives the MCPC player a default skin set by the server. ;)

**Comment by DefinitlyEvil** [comment]
@SenanYT I did, in `/deafaults/SKIN.BIN`. Server transfers skin in PlayerListPacket but I don't think I implemented it well.

**Comment by RazvanDu** [comment]
I'll take a look as soon as possible.

**Comment by RazvanDu** [comment]
Another issue is that the server doesn't appear in the server list but I've already fixed it lol, btw would you mind giving me write access so I don't have to make a pull request for small things?

**Comment by RazvanDu** [comment]
Btw, I think you forgot to write the length of the skin byte array in the PlayerListPacket ;c.

Also I think the first byte of the skin is slim and the seconds one is alpha not sure tho.

**Comment by DefinitlyEvil** [comment]
@SenanYT Will do later today.

**Comment by KangYui** [comment]
Please add bug: Missing PlayerList on MCPE

**Comment by RazvanDu** [comment]
The skin issue is fixed!

**Comment by jlirochon** [comment]
@SenanYT @DefinitlyEvil could you check that all unresolved bug has his own issue  attached to milestone 0.0.3, then close this one ?

**Comment by DefinitlyEvil** [comment]
I think they are all created.
